env:
- name: SVELTE_APP_REMOTE_URL
  value: "http://myapp-dev-ns99-myapp-gruim.test"
- name: CONTAINER_NAME
  value: "myappdevns99myappgruim"
# - name: DEV
#   value: "true"


gras-deploy: 
  # gras: 
  #   ssl: false
  grapi:
    ssl: false
  gruim:
    ssl: false


ingress:
  enabled: true
  hosts:
    - host: myapp.test
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
