apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: "{{ .APP }}"
build:
  artifacts:
    # - image: "app-test"
    #   docker:
    #     dockerfile: Dockerfile.test
    - image: "grapp" # grapple application
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: ["sh", "-c", "./before.sh"]
            os: [darwin, linux]
      #   after:
      #     - command: ["sh", "-c", "./publish.sh"]
      #       os: [darwin, linux]
  tagPolicy:
    # dateTime: {}
    gitCommit: {}
deploy:
  statusCheckDeadlineSeconds: 1200
  helm:
    releases:
      - name: "grapp"
        chartPath: chart
        valuesFiles:
          - chart/values.yaml
        setValueTemplates:
          env[0].value: "http://myapp-dev-ns99-myapp-gruim.grpl-cli.grapple-demo.com/dashboard.json"
        version: 0.1.0
        namespace: "{{ .IMAGE_NAME }}-{{ .IMAGE_TAG }}"
        createNamespace: true
        packaged: 
          version: 0.1.0
          appVersion: 0.1.0
    # hooks:
    #   before:
    #   - host:
    #       command: ["sh", "-c", "./before.sh"]
    #       os: [darwin, linux]
portForward:
  - resourceType: service
    resourceName: "myapp"
    port: 80
    # localPort: 8080
    namespace: "{{ .IMAGE_NAME }}-{{ .IMAGE_TAG }}"
  # - resourceType: service
  #   resourceName: api
  #   port: 80
  #   localPort: 9999
test:
  - image: busybox
    custom:
      - command: ./test/*.sh
        timeoutSeconds: 1200
profiles:
  - name: minikube
    activation:
      - command: dev
        kubeContext: minikube
      - command: delete
        kubeContext: minikube
      - command: build
        kubeContext: minikube
    patches:
    - op: add
      path: /deploy/helm/releases/0/valuesFiles/1
      value: "chart/values-minikube.yaml"
  - name: dev
    activation:
      - command: dev
    patches:
    - op: add
      path: /deploy/helm/releases/0/valuesFiles/1
      value: "chart/values-dev.yaml"
    # - op: add
    #   path: /deploy/helm/releases/0/setValues/ingress/hosts/0/host
    #   value: "{{.APP}}{{.NAMESPACE}}.{{.CLUSTERDOMAIN}}"
    - op: replace
      path: /deploy/helm/releases/0/name
      value: "{{.APP}}"
    - op: replace
      path: /deploy/helm/releases/0/namespace
      value: "{{ .NAMESPACE }}"
  - name: nop
    activation:
      - env: ENV=nop
    # patches:
    # - op: replace
    #   path: /deploy/helm/releases/0/namespace
    #   value: "{{ .NAMESPACE }}"
  - name: uat
    activation:
      - env: ENV=uat
    # patches:
    # - op: replace
    #   path: /deploy/helm/releases/0/namespace
    #   value: "{{ .NAMESPACE }}"
  - name: prod
    activation:
      - env: ENV=production
    # patches:
    # - op: replace
    #   path: /deploy/helm/releases/0/namespace
    #   value: "{{ .APP }}"
